"""Build version resolution for ``GET /version`` and audit rows.

Resolution order (#3517), first source that yields a JSON object wins:

1. the ``version_file`` setting — the operator/dev-provided file (the
   host image's baked ``/home/klangk/version.json``, the devenv's
   seeded ``.devenv/state/klangk/version.json``, a CI override);
2. the copy packaged inside the klangk wheel at ``klangk/version.json``
   — generated by ``scripts/generate-version.sh`` at wheel-build time
   (the hatch build hook force-includes it), so a deployed host whose
   operator ``klangkd.yaml`` mounts over the image's config file and
   omits ``version_file`` still reports the real build, not ``dev``;
3. the dev block — a source checkout / editable install with no
   version source (the devenv always configures source 1).

Every source is read with the #3329 tolerance: an absent, unreadable,
or wrong-shaped file falls through to the next source instead of
raising.
"""

from __future__ import annotations

import json
from importlib.resources import files

DEV_BLOCK = {"version": "dev", "commit": "unknown", "built_at": None}


def read_version_file(path: str) -> dict | None:
    """The parsed JSON object at ``path``, or ``None`` (#3329 tolerance)."""
    try:
        with open(path) as f:
            info = json.load(f)
    except OSError, ValueError:
        return None
    return info if isinstance(info, dict) else None


def packaged_version() -> dict | None:
    """The wheel-packaged ``klangk/version.json``, or ``None``.

    Absent in editable installs and source checkouts — the file only
    exists inside a built wheel (#3517).
    """
    try:
        info = json.loads(files("klangk").joinpath("version.json").read_text())
    except OSError, ValueError:
        return None
    return info if isinstance(info, dict) else None


def version_info(settings) -> dict:
    """The running build's version info dict (see module docstring).

    Callers own the returned dict (the endpoint adds ``features``), so
    no shared object is handed out — every source builds a fresh dict
    and the dev block is copied.
    """
    path = settings.version_file
    if path and (info := read_version_file(path)):
        return info
    if info := packaged_version():
        return info
    return dict(DEV_BLOCK)
