[supervisord]
nodaemon=true
user=klangk
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:uvicorn]
command=python3 -m uvicorn klangk_backend.main:app
    --host 0.0.0.0
    --port %(ENV_KLANGK_PORT)s
    --ws-max-size 65536
    --ws-ping-interval 20
    --ws-ping-timeout 20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
stopasgroup=true
killasgroup=true
priority=10

[program:nginx]
command=%(ENV_HOME)s/bin/nginx
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=20
