[storage]
driver = "overlay"
runroot = "/run/user/1000"
graphroot = "/home/klangk/.local/share/containers/storage"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"
