#!/usr/bin/env bash
# Create a stub klangk_plugins package so flutter pub get works without
# running the full import_dart_plugins.py codegen. Useful for CI and
# first-time checkouts before plugins are materialized.
#
# This is a *dev-shell/CI convenience* only — the real build
# (flutterbuildweb.sh / build-*-image.sh) materializes plugins into its own
# tempdir and runs the full codegen there (#1660). The stub lives at a
# persistent path so the symlink it creates at src/frontend/pubspec_overrides.yaml
# stays valid between commands; a build will repoint that symlink at its
# tempdir while it runs, and this stub (re-run on the next shell entry /
# CI step) restores it.
#
# Usage: bash scripts/stub_dart_plugins.sh [stub-dir]
#   stub-dir defaults to ${XDG_STATE_HOME:-$HOME/.local/state}/klangk/dart-stub
#
# Skips if pubspec_overrides.yaml already exists with a non-dangling target
# (real plugins are set up).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="$REPO_ROOT/src/frontend"

if [ -e "$FRONTEND_DIR/pubspec_overrides.yaml" ]; then
  # Symlink exists and resolves (non-dangling) — real plugins (or a prior
  # stub) are in place. `-e` follows the symlink and is false if it dangles.
  exit 0
fi

STUB_DIR="${1:-${XDG_STATE_HOME:-$HOME/.local/state}/klangk/dart-stub}"
mkdir -p "$STUB_DIR/lib"

cat >"$STUB_DIR/pubspec.yaml" <<'EOF'
name: klangk_plugins
publish_to: none
version: 0.0.1
environment:
  sdk: ^3.6.0
  flutter: ^3.27.0
dependencies:
  flutter:
    sdk: flutter
  klangk_plugin_api:
    git:
      url: https://github.com/mcdonc/klangk-plugin-api.git
      ref: v0.2.0
EOF

cat >"$STUB_DIR/lib/klangk_plugins.dart" <<'EOF'
// Stub — no plugins. Generated by scripts/stub_dart_plugins.sh
import 'package:klangk_plugin_api/klangk_plugin_api.dart';
List<ToolPlugin> createAllPlugins() => [];
// Empty named-plugins list — the active-set filter in main.dart iterates
// this (createAllNamedPlugins) and registers nothing (#1655).
List<({String name, ToolPlugin plugin})> createAllNamedPlugins() => [];
EOF

# Write overrides file and symlink into frontend
OVERRIDES="$STUB_DIR/pubspec_overrides.yaml"
cat >"$OVERRIDES" <<EOF
dependency_overrides:
  klangk_plugins:
    path: $STUB_DIR
EOF
ln -sf "$OVERRIDES" "$FRONTEND_DIR/pubspec_overrides.yaml"

echo "Created stub klangk_plugins at $STUB_DIR"
