"""Plugin configuration: load declared config keys and resolve values.

Reads the merged plugin config manifest generated by
``scripts/collect_plugin_config.py`` and resolves each declared key from
the server environment.  Provides helpers to retrieve values by scope
(container, frontend, or both).
"""

import json
import logging
import os

logger = logging.getLogger(__name__)

_PLUGINS_DIR = os.environ.get("KLANGK_PLUGINS_DIR") or os.path.join(
    os.path.expanduser("~"), ".klangk", "plugins"
)
_CONFIG_PATH = os.path.join(_PLUGINS_DIR, ".plugin_config.json")

# Loaded at startup: {env_key: {plugin, description, default, scope}}
_declarations: dict[str, dict] = {}

# Resolved values: {env_key: str}
_values: dict[str, str] = {}


def load() -> None:
    """Load plugin config declarations and resolve values from env."""
    global _declarations, _values  # noqa: PLW0603
    _declarations = {}
    _values = {}

    if not os.path.isfile(_CONFIG_PATH):
        return

    try:
        with open(_CONFIG_PATH) as f:
            _declarations = json.load(f)
    except (json.JSONDecodeError, ValueError, OSError) as exc:
        logger.warning(
            "Failed to load plugin config %s: %s", _CONFIG_PATH, exc
        )
        return

    for key, spec in _declarations.items():
        default = spec.get("default", "")
        _values[key] = os.environ.get(key, default)

    if _declarations:
        logger.info(
            "Loaded %d plugin config key(s): %s",
            len(_declarations),
            ", ".join(sorted(_declarations)),
        )


def container_env() -> dict[str, str]:
    """Return env vars to inject into workspace containers."""
    result = {}
    for key, spec in _declarations.items():
        scope = spec.get("scope", "container")
        if scope in ("container", "both"):
            result[key] = _values.get(key, "")
    return result


def frontend_config() -> dict[str, str]:
    """Return config entries for the GET /api/config response.

    Keys are lowercased for JSON convention (e.g. SOLIPLEX_URL → soliplex_url).
    """
    result = {}
    for key, spec in _declarations.items():
        scope = spec.get("scope", "container")
        if scope in ("frontend", "both"):
            result[key.lower()] = _values.get(key, "")
    return result
